### ISSUE TITLE
Impersonation issue

### ISSUE THREAD

**Issue by nobe4** [github/privileged-requester#166]
The current checks uses `author name` to ensure that the changes were made by the expected user.

https://github.com/github/privileged-requester/blob/fdd9f579ce88b2494b874bb381b966777473c3c3/src/runner.js#L16-L23

It is however really easy to make a commit with a different name, or email address.

```
git -c user.name='Linus Torvalds' -c user.email='torvalds@linux-foundation.org' commit -m "Wow, this is definitely legit."
```

This poses a serious risk of impersonation.

**Comment by nobe4** [comment]
The [GitHub API](https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#list-commits-on-a-pull-request), provide `commit verification` information that is parsed in https://github.com/github/privileged-requester/blob/fdd9f579ce88b2494b874bb381b966777473c3c3/src/runner.js#L16


Format:
```json
      "verification": {
        "verified": false,
        "reason": "unsigned",
        "signature": null,
        "payload": null
      }
```

E.g. `gh api /repos/X/Y/pulls/Z/commits | jq '.[].commit.verification'`:
```json
{
  "payload": null,
  "reason": "unsigned",
  "signature": null,
  "verified": false
},
{
  "payload": "tree xxx\nparent yyy\nparent 76508bebf310e1152c0d423465a35883b42b306a\nauthor nobe4 <nobe4@users.noreply.github.com>...",
  "reason": "valid",
  "signature": "-----BEGIN PGP SIGNATURE-----\n\nwsFcBA...n-----END PGP SIGNATURE-----\n",
  "verified": true
}
```

It is possible to add:

```diff
    for (const [, commit] of Object.entries(this.pullRequest.listCommits())) {
      let commitAuthor = commit.author.login.toLowerCase();

+     if (!commit.verification.verified) {
+               core.warning("Unexpected unverified commit.");
+       return false.
+     }

      if (commitAuthor !== privileged_requester_username) {
        core.warning(
          `Unexpected commit author found by ${commitAuthor}! Commits should be authored by ${privileged_requester_username} I will not proceed with the privileged reviewer process.`,
        );
        return false;
      }
    }
```

**Comment by GrantBirki** [comment]
@nobe4 I'll work on implementing this 🚀
